name: functions_client
description: A dart client library for the Supabase functions.
version: 0.0.1-dev.2
homepage: 'https://supabase.io'
repository: 'https://github.com/supabase-community/functions-dart'

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  http: ^0.13.4

dev_dependencies:
  dotenv: ^3.0.0
  lint: ^1.5.1
  test: ^1.16.4
